services:
  oauth2-proxy:
    container_name: clearml-oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: unless-stopped
    depends_on:
      - webserver
    command:
      - --provider=github
      - --client-id=${OAUTH2_PROXY_CLIENT_ID}
      - --client-secret=${OAUTH2_PROXY_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_PROXY_COOKIE_SECRET}
      - --email-domain=*
      - --upstream=http://webserver:80
      - --http-address=0.0.0.0:4180
      - --redirect-url=https://${OAUTH2_DOMAIN_NAME}/oauth2/callback
      - --cookie-expire=6h
      - --cookie-secure=false
      - --pass-access-token=true
      - --pass-user-headers=true
      - --set-xauthrequest=true
      - --skip-provider-button=false
    ports:
      - "4180:4180"
    networks:
      - frontend
      - backend
